### ISSUE TITLE
Segmentation fault in rapidjson

### ISSUE THREAD

**Issue by siyuanwu99** [qwerty35/lsc_dr_planner#1]
Hello Jungwon,

First of all, thank you very much for providing the software of your paper!

I tried to run your package on Ubuntu 20.04 with ROS noetic but it crushed. I tried to debug and got a segmentation fault at the following line:

https://github.com/qwerty35/lsc_dr_planner/blob/110610c31732ed298e803650f03ec49cb6a804d8/include/rapidjson/filewritestream.h#L65

**Comment by qwerty35** [comment]
First of all, thank you for your attention.
I recently modified the code for that part, so make sure the package is the latest version.
If it does not work, please let me know the following:
1. Launch file that makes the problem.
2. Full debug message when the seg fault occurs.

Thank you.
Jungwon Park.

**Comment by siyuanwu99** [comment]
Thanks for your reply! It's really helpful. Now the issue is solved.
